[package]
name = "advent-rs"
version = "0.1.0"
authors = ["Joanna Doyle <jjadoyle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
bitvec = "0.22"
num = "0.4"
hex = "0.4"